#!/bin/bash
rnn_type_array=("LeakyRNN")
activation_array=("softplus")
init_array=("diag")
for rnn_type in ${rnn_type_array[*]};do
for activation in ${activation_array[*]};do
for init in ${init_array[*]};do
for n_rnn in 128;do
for l2w in -6;do
for l2h in -6;do
for l1w in -0;do
for l1h in -0;do
for seed in 2;do
for lr in -6;do
for sigma_rec in 1;do
for sigma_x in 2;do
for pop_rule in {0..14};do
sbatch -p shenoy leave_one_out_"$rnn_type"_"$activation"_"$init"_"$n_rnn"_"$l2w"_"$l2h"_"$l1w"_"$l1h"_"$seed"_"$lr"_"$sigma_rec"_"$sigma_x"_"$pop_rule"
done
done
done
done
done
done
done
done
done
done
done
done
done
